export const proficiencyLevels =  ["Beginner", "Intermediate", "Advanced", "Expert"];


const actualArr = [
    {
        category: "Technical Skills",
        subcategories: [
            "Programming Languages",
            "Web Development",
            "Mobile Development",
            "Backend Development",
            "DevOps/Cloud",
            "Database Management",
            "Data Analysis",
            "Machine Learning/AI",
            "Cybersecurity",
            "Software Testing/QA",
            "Embedded Systems",
            "Networking",
        ],
    },
    {
        category: "Tools and Technologies",
        subcategories: [
            "IDEs and Editors",
            "CI/CD Tools",
            "Cloud Platforms (e.g., AWS, Azure, Google Cloud)",
            "Collaboration Tools (e.g., Jira, Trello, Asana)",
            "Version Control (e.g., Git, GitHub)",
            "Data Visualization Tools (e.g., Tableau, Power BI)",
            "Design Tools (e.g., Figma, Adobe XD, Canva)",
            "Office Suites (e.g., MS Office, Google Workspace)",
        ],
    },
    {
        category: "Soft Skills",
        subcategories: [
            "Leadership",
            "Communication",
            "Team Collaboration",
            "Conflict Resolution",
            "Problem-Solving",
            "Critical Thinking",
            "Time Management",
            "Emotional Intelligence",
        ],
    },
    {
        category: "Business Skills",
        subcategories: [
            "Project Management",
            "Product Management",
            "Business Analysis",
            "Market Research",
            "Financial Analysis",
            "Budgeting and Forecasting",
            "Stakeholder Management",
        ],
    },
    {
        category: "Certifications and Frameworks",
        subcategories: [
            "Agile and Scrum",
            "ITIL",
            "PMP (Project Management Professional)",
            "Six Sigma",
            "Industry-Specific Certifications (e.g., CPA, CFA)",
            "Frameworks (e.g., Django, React, Angular)",
        ],
    },
    {
        category: "Design and Creativity",
        subcategories: [
            "UI/UX Design",
            "Graphic Design",
            "Motion Graphics",
            "Photography and Video Editing",
            "Content Writing",
            "Copywriting",
            "Branding and Marketing Design",
        ],
    },
    {
        category: "Marketing and Sales",
        subcategories: [
            "Digital Marketing",
            "SEO/SEM",
            "Social Media Marketing",
            "Email Marketing",
            "Sales Strategy",
            "Lead Generation",
            "CRM Tools (e.g., Salesforce, HubSpot)",
        ],
    },
    {
        category: "Language and Communication",
        subcategories: [
            "Foreign Languages (e.g., French, Spanish, Mandarin)",
            "Public Speaking",
            "Negotiation Skills",
            "Technical Writing",
            "Editing and Proofreading",
            "Translation",
        ],
    },
    {
        category: "Industry-Specific Skills",
        subcategories: [
            "Healthcare (e.g., Medical Coding, Patient Care)",
            "Legal (e.g., Legal Research, Case Management)",
            "Education (e.g., Curriculum Development, Teaching)",
            "Manufacturing (e.g., CNC Programming, Safety Standards)",
            "Retail (e.g., Inventory Management, Customer Service)",
        ],
    },
    {
        category: "Miscellaneous",
        subcategories: [
            "Data Entry",
            "Research Skills",
            "Event Planning",
            "Logistics and Supply Chain",
            "Risk Management",
            "Ethical Hacking",
        ],
    },
];

export const availableSkillsData = [
    // Technical Skills Domain
    { id: "1", domainId: null, isDomain: true, value: "Technical Skills" },
    { id: "2", domainId: "1", isDomain: false, value: "Programming Languages" },
    { id: "3", domainId: "1", isDomain: false, value: "Web Development" },
    { id: "4", domainId: "1", isDomain: false, value: "Mobile Development" },
    { id: "5", domainId: "1", isDomain: false, value: "Backend Development" },
    { id: "6", domainId: "1", isDomain: false, value: "DevOps/Cloud" },
    { id: "7", domainId: "1", isDomain: false, value: "Database Management" },
    { id: "8", domainId: "1", isDomain: false, value: "Data Analysis" },
    { id: "9", domainId: "1", isDomain: false, value: "Machine Learning/AI" },
    { id: "10", domainId: "1", isDomain: false, value: "Cybersecurity" },
    { id: "11", domainId: "1", isDomain: false, value: "Software Testing/QA" },
    { id: "12", domainId: "1", isDomain: false, value: "Embedded Systems" },
    { id: "13", domainId: "1", isDomain: false, value: "Networking" },
  
    // Tools and Technologies Domain
    { id: "14", domainId: null, isDomain: true, value: "Tools and Technologies" },
    { id: "15", domainId: "14", isDomain: false, value: "IDEs and Editors" },
    { id: "16", domainId: "14", isDomain: false, value: "CI/CD Tools" },
    { id: "17", domainId: "14", isDomain: false, value: "Cloud Platforms (e.g., AWS, Azure, Google Cloud)" },
    { id: "18", domainId: "14", isDomain: false, value: "Collaboration Tools (e.g., Jira, Trello, Asana)" },
    { id: "19", domainId: "14", isDomain: false, value: "Version Control (e.g., Git, GitHub)" },
    { id: "20", domainId: "14", isDomain: false, value: "Data Visualization Tools (e.g., Tableau, Power BI)" },
    { id: "21", domainId: "14", isDomain: false, value: "Design Tools (e.g., Figma, Adobe XD, Canva)" },
    { id: "22", domainId: "14", isDomain: false, value: "Office Suites (e.g., MS Office, Google Workspace)" },

    { id: "23", domainId: null, isDomain: true, value: "Soft Skills" },
    { id: "24", domainId: "23", isDomain: false, value: "Leadership" },
    { id: "25", domainId: "23", isDomain: false, value: "Communication" },
    { id: "26", domainId: "23", isDomain: false, value: "Team Collaboration" },
    { id: "27", domainId: "23", isDomain: false, value: "Conflict Resolution" },
    { id: "28", domainId: "23", isDomain: false, value: "Problem-Solving" },
    { id: "29", domainId: "23", isDomain: false, value: "Critical Thinking" },
    { id: "30", domainId: "23", isDomain: false, value: "Time Management" },
    { id: "31", domainId: "23", isDomain: false, value: "Emotional Intelligence" },

    { id: "32", domainId: null, isDomain: true, value: "Business Skills" },
    { id: "33", domainId: "32", isDomain: false, value: "Project Management" },
    { id: "34", domainId: "32", isDomain: false, value: "Product Management" },
    { id: "35", domainId: "32", isDomain: false, value: "Business Analysis" },
    { id: "36", domainId: "32", isDomain: false, value: "Market Research" },
    { id: "37", domainId: "32", isDomain: false, value: "Financial Analysis" },
    { id: "38", domainId: "32", isDomain: false, value: "Budgeting and Forecasting" },
    { id: "39", domainId: "32", isDomain: false, value: "Stakeholder Management" },
  
    { id: "39", domainId: "32", isDomain: true, value: "Certifications and Frameworks" },
    { id: "40", domainId: "39", isDomain: false, value: "Agile and Scrum" },
    { id: "41", domainId: "39", isDomain: false, value: "ITIL" },
    { id: "42", domainId: "39", isDomain: false, value: "PMP (Project Management Professional)" },
    { id: "43", domainId: "39", isDomain: false, value: "Six Sigma" },
    { id: "44", domainId: "39", isDomain: false, value: "Industry-Specific Certifications (e.g., CPA, CFA)" },
    { id: "45", domainId: "39", isDomain: false, value: "Frameworks (e.g., Django, React, Angular)" },
    
    { id: "46", domainId: "32", isDomain: true, value: "Design and Creativity" },
    { id: "47", domainId: "46", isDomain: false, value: "UI/UX Design" },
    { id: "48", domainId: "46", isDomain: false, value: "Graphic Design" },
    { id: "49", domainId: "46", isDomain: false, value: "Motion Graphics" },
    { id: "50", domainId: "46", isDomain: false, value: "Photography and Video Editing" },
    { id: "51", domainId: "46", isDomain: false, value: "Content Writing" },
    { id: "52", domainId: "46", isDomain: false, value: "Copywriting" },
    { id: "53", domainId: "46", isDomain: false, value: "Branding and Marketing Design" },
    
    { id: "54", domainId: "32", isDomain: true, value: "Marketing and Sales" },
    { id: "55", domainId: "54", isDomain: false, value: "Digital Marketing" },
    { id: "56", domainId: "54", isDomain: false, value: "SEO/SEM" },
    { id: "57", domainId: "54", isDomain: false, value: "Social Media Marketing" },
    { id: "58", domainId: "54", isDomain: false, value: "Email Marketing" },
    { id: "59", domainId: "54", isDomain: false, value: "Sales Strategy" },
    { id: "60", domainId: "54", isDomain: false, value: "Lead Generation" },
    { id: "61", domainId: "54", isDomain: false, value: "CRM Tools (e.g., Salesforce, HubSpot)" },
    
    { id: "62", domainId: "32", isDomain: true, value: "Language and Communication" },
    { id: "63", domainId: "62", isDomain: false, value: "Foreign Languages (e.g., French, Spanish, Mandarin)" },
    { id: "64", domainId: "62", isDomain: false, value: "Public Speaking" },
    { id: "65", domainId: "62", isDomain: false, value: "Negotiation Skills" },
    { id: "66", domainId: "62", isDomain: false, value: "Technical Writing" },
    { id: "67", domainId: "62", isDomain: false, value: "Editing and Proofreading" },
    { id: "68", domainId: "62", isDomain: false, value: "Translation" },
    
    { id: "69", domainId: "32", isDomain: true, value: "Industry-Specific Skills" },
    { id: "70", domainId: "69", isDomain: false, value: "Healthcare (e.g., Medical Coding, Patient Care)" },
    { id: "71", domainId: "69", isDomain: false, value: "Legal (e.g., Legal Research, Case Management)" },
    { id: "72", domainId: "69", isDomain: false, value: "Education (e.g., Curriculum Development, Teaching)" },
    { id: "73", domainId: "69", isDomain: false, value: "Manufacturing (e.g., CNC Programming, Safety Standards)" },
    { id: "74", domainId: "69", isDomain: false, value: "Retail (e.g., Inventory Management, Customer Service)" },
    
    { id: "75", domainId: "32", isDomain: true, value: "Miscellaneous" },
    { id: "76", domainId: "75", isDomain: false, value: "Data Entry" },
    { id: "77", domainId: "75", isDomain: false, value: "Research Skills" },
    { id: "78", domainId: "75", isDomain: false, value: "Event Planning" },
    { id: "79", domainId: "75", isDomain: false, value: "Logistics and Supply Chain" },
    { id: "80", domainId: "75", isDomain: false, value: "Risk Management" },
    { id: "81", domainId: "75", isDomain: false, value: "Ethical Hacking" },
    
    
];
  
  