import type { Metadata } from "next";
import "./globals.css";
import "../css/custom-scrollbar.css";
import Topbar from "@/components/topbar/Topbar";
import Sidebar from "@/shared/sidebar/Sidebar";
import Providers from "./Providers";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <Providers>
                    <main className="flex w-screen">
                        {/* <section className="min-h-screen w-[5%] bg-red-500 " >
    <Sidebar />
    </section> */}
                        <section 
                            className={`min-h-screen w-[100%] flex flex-col transition-all duration-500 
        bg-gradient-to-br from-gray-100 to-rose-100 dark:from-gray-900 dark:to-gray-800`}
                        >
                            <div className="sticky top-0 z-10">
                                <Topbar />
                            </div>
                            <div className="flex-1">
                                {children}
                            </div>
                        </section>
                    </main>

                </Providers>
            </body>
        </html>
    );
}
